[FLAG-997] GADM coutry list
wri/gfw pull request #4891
Opened 2024-11-25 14:55 UTC by willian-viana

## Overview

Brief description of what this PR does, and why it is needed.

## Demo

If applicable: screenshots, gifs, etc.

## Notes

If applicable: ancilary topics, caveats, alternative strategies that didn't work out, etc.

## Testing

- Include any steps to verify the features this PR introduces.
- If this fixes a bug, include bug reproduction steps.

2024-12-18 18:21 UTC, willian-viana commented on providers/country-data-provider/actions.js
> +              id: parseGadm36Id(row.id).adm2,
Change the method name to cover 4.1 instead of 3.6

2025-01-16 20:39 UTC, willian-viana commented on services/country.js
> +const GADM_DATASET = '/dataset/gadm_administrative_boundaries/v4.1/query';
@manukala6 @gtempus @dmannarino this service is responsible for populating the regions list.

2025-01-24 18:43 UTC, wri7tno approved these changes

2025-01-24 18:43 UTC, wri7tno commented on services/location.js
> -import { cartoRequest } from 'utils/request';
farewell cartoReuest 👍

2025-01-24 18:43 UTC, wri7tno commented on utils/gadm.js
> +export const getGadmId = (country, region, subRegion) =>
great idea to rename it 👍

2025-01-27 15:18 UTC, gtempus commented on utils/gadm.js
> +export const getGadmId = (country, region, subRegion) =>
I agree. Well done!

2025-01-27 16:19 UTC, gtempus requested changes
Love the improvements and additional tests added in this PR, Will. Well done! I do have a suggested refactor for `location.js` if you agree.

2025-01-27 16:19 UTC, gtempus commented on services/__tests__/country.spec.js
> +describe('country service', () => {
Love these tests, Will! 💪
Your descriptions are very detailed and really contribute to the value of these tests.

2025-01-27 16:19 UTC, gtempus commented on services/__tests__/country.spec.js
> +        `${GADM_DATASET}?sql=${SQL_QUERIES.getGADMRegions}`.replace(
I don't really like the `replace` calls.

The reason is that it's a duplication of how the `getRegionsProvider` method is implemented internally. This test could break if we decide to change how the values get replaced someday even though the interface with `dataRequest` remains unchanged.

I would recommend always using literal values in `expect` matchers:
`SELECT name_1 AS name, gid_1 AS id FROM gadm_administrative_boundaries WHERE adm_level='1' AND gid_0 = 'BRA' ORDER BY name`

2025-01-27 16:19 UTC, gtempus commented on services/location.js
> +export const countryConfig = {
I would encourage you to try to remove the duplication in `countryConfig`.
`adm0`, `adm1`, and `adm2` build on each other. Your current implementation reimplements the previous `adm` level in each case.

2025-01-27 16:19 UTC, gtempus commented on services/__tests__/location.spec.js
> +describe('countryConfig', () => {
Having these great tests should be very helpful if you decide to tackle my recommended refactor of `countryConfig` mentioned earlier in this review.

2025-01-27 16:39 UTC, willian-viana commented on services/country.js
>      'SELECT iso, country AS name FROM data WHERE 1 = 1 AND year = 2020',
It was me in a different PR haha I don't know, I probably forgot to remove it. I'll do it know.

2025-01-27 16:50 UTC, willian-viana commented on services/location.js
> +export const countryConfig = {
You are completely right. I was thinking about this last week. I've decided the effort to create a generic method for this configuration wouldn't be worth since the methods I'm reusing here doesn't fit the return I need. I'll try a different approach though.

2025-01-27 18:15 UTC, willian-viana commented on services/__tests__/location.spec.js
> +describe('countryConfig', () => {
It was very helpful! haha

2025-01-27 21:42 UTC, gtempus commented on services/location.js
> +export const countryConfig = {
Love it, Will! Nice refactor! 💪

2025-01-27 21:44 UTC, gtempus approved these changes
Looks great, @willian-viana! Well done. 🤓 🎨

2025-04-01 15:06 UTC, gtempus approved these changes
Hi, @willian-viana! The changes for [FLAG-1287](https://gfw.atlassian.net/browse/FLAG-1287) look great. 💯

2025-04-01 15:06 UTC, gtempus commented on components/map-menu/actions.js
> +
Nice! I'm glad removing the analysis modal wasn't complicated, @willian-viana . 😅

2025-04-01 15:06 UTC, gtempus commented on services/geocoding.js
> +      `/geocoding/v5/mapbox.places/${searchQuery}.json?language=${lang}&access_token=${process.env.NEXT_PUBLIC_MAPBOX_TOKEN}&types=postcode,district,place,locality,neighborhood,address,poi`,
Look at all of that carto code vanish! 🙌 
All of that complexity, and it wasn't even doing anything useful anymore. 😑

2025-04-28 21:41 UTC, manukala6 commented
@willian-viana Thanks for the corrections, the PR looks good now

2025-04-28 21:41 UTC, manukala6 approved these changes

2025-04-29 15:32 UTC, merged